<?php
/**
 * Product app list view home
 *
 * @var $block Custom\Blocktemplate\Block\Productapplist
 */
?>
<!--<h1><?php echo $block->getTitle(); ?></h1>-->
<section class="appzBox block">
          <section class="appslist block-new-products">

                <div class="block-title">Recent Apps</div>
                <!-- <p id="store_sub">Single Store</p> -->
                <ul class="block-content">
                    <li>
                      <div id="app_pic">
                        <img src="http://159.203.151.92/customimages/appIcon1.png">
                      </div>
                      <div id="app_desc">
                          <p>App Template 1</p>
                          <span><img src="http://159.203.151.92/customimages/rating.png"></span>
                      </div> 
                      <div id="app_store_links">
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/appleicon2.png"></a>
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/playstoreicon3.png"></a>
                      </div>
                    </li>

                    <li>
                      <div id="app_pic">
                        <img src="http://159.203.151.92/customimages/appIcon2.png">
                      </div>
                      <div id="app_desc">
                          <p>App Template 2</p>
                          <span><img src="http://159.203.151.92/customimages/rating.png"></span>
                      </div> 
                      <div id="app_store_links">
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/appleicon2.png"></a>
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/playstoreicon3.png"></a>
                      </div>
                    </li>

                    <li>
                      <div id="app_pic">
                        <img src="http://159.203.151.92/customimages/appIcon3.png">
                      </div>
                      <div id="app_desc">
                          <p>App Template 2</p>
                          <span><img src="http://159.203.151.92/customimages/rating.png"></span>
                      </div> 
                      <div id="app_store_links">
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/appleicon2.png"></a>
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/playstoreicon3.png"></a>
                      </div>
                    </li>

                    <li>
                      <div id="app_pic">
                        <img src="http://159.203.151.92/customimages/appIcon4.png">
                      </div>
                      <div id="app_desc">
                          <p>App Template 2</p>
                          <span><img src="http://159.203.151.92/customimages/rating.png"></span>
                      </div> 
                      <div id="app_store_links">
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/appleicon2.png"></a>
                          <a href="http://159.203.151.92/AppMa/"><img src="http://159.203.151.92/customimages/playstoreicon3.png"></a>
                      </div>
                    </li>
                </ul>
          </section>
          <!-- <button>See More</button> -->
      </section>