<?php
/**
 * Product category view template
 *
 * @var $block Custom\Blocktemplate\Block\Productcategory
 */
?>
<?php
/* $helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner=$helper->getSeller();
print_r($partner); */

        $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
		
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
         $basepath=$storeManager->getStore()->getBaseUrl();          
		
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
	   $sql3 = "Select * FROM catalog_category_entity b where  b.parent_id=2 ";
		$result3 = $connection->fetchAll($sql3);
		//echo"<pre>";print_r($result3);
		$result4='';
		 foreach($result3 as $data)
		{ 
			 
			$categoryId =$data['entity_id'];
			$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			$object_manager = $_objectManager->create('Magento\Catalog\Model\Category')
			->load($categoryId);
			
			$subcats  =$object_manager->getChildren();
			$subcategories = array();
			//print_r($subcats);
			 foreach(explode(',',$subcats) as $subCatid){
				// $objectManagerr = \Magento\Framework\App\ObjectManager::getInstance();
                 //   $categoryFactory = $objectManagerr->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
                $_subCategory = $_objectManager->create('Magento\Catalog\Model\Category')->load($subCatid);
						   if($_subCategory->getIsActive()) {
					$subcategories[] = array('id'=>$_subCategory->getId(),'name'=>$_subCategory->getName(),'image_url'=>$_subCategory->getImageUrl(),'sub_category_url'=>$_subCategory->getUrl()); 
				}
			}
			//print_r($subcategories);
			 
				$result4[]=array('category_id'=>$data['entity_id'],'category_name'=>$object_manager->getName(),'image_url'=>$object_manager->getImageUrl(),'category_url'=>$object_manager->getUrl(),'sub_category'=>$subcategories);  
			
			//print_r($result4);
		} 
		//echo"<pre>"; print_r($result4); 
?>
<!--<h1><?php echo $block->getTitle(); ?></h1>-->
<section class="categoryBOX container-fluid">
<div class="row">

<?php 
$c=1;
foreach ($result4 as $val)
{
	
	?>
	
	<div class="col-xs-12 col-sm-12 col-md-4 ">
<div class="tub"><?php if($val['image_url']!=''){?>
<img alt="<?php echo $val['category_name'];?>" src="<?php echo  $val['image_url'];?>" class="img-responsive">
<?php } else {?>
<img style="height: 243px;" alt="<?php echo $val['category_name'];?>" src="<?php echo $basepath;?>customimages/defaultcatimage.jpg" class="img-responsive">
<?php }  ?>
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title"><?php echo $val['category_name'];?></p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<?php foreach($val['sub_category'] as $subcat) { ?>
<li><?php echo $subcat['name']; ?></li>
<?php } ?>
<li><a href="<?php echo $val['category_url'];?>" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
<?php if($c%3==0) { echo '</div><div class="row">'; } ?>
	<?php
	$c++;
}

?>
</div>
</section> 
<!--
<section class="categoryBOX container-fluid">
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-4 ">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/kitchenapp.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">HOME</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>Appliances</li>
<li>Furniture</li>
<li>Decor/Furnishing</li>
<li>Kitchen</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-4">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/books.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">MEDIA</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>SmartPhones</li>
<li>Laptops</li>
<li>Pen Drives</li>
<li>Memory Cards</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-4">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/electronics.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">Electronics</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>SmartPhones</li>
<li>Laptops</li>
<li>Pen Drives</li>
<li>Memory Cards</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-4 ">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/men.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">MEN</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>SmartPhones</li>
<li>Laptops</li>
<li>Pen Drives</li>
<li>Memory Cards</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-4">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/women.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">WOMEN</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>SmartPhones</li>
<li>Laptops</li>
<li>Pen Drives</li>
<li>Memory Cards</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-4">
<div class="tub"><img alt="Williams 20 Hambart (Dos Cardtos)" src="http://159.203.151.92/customimages/home.jpg" class="img-responsive">
<div class="banner-content row">
<div class="col-md-6 col-sm-6 col-xs-6">
<p class="banner-cat">Category</p>
<p class="banner-title">Computer &amp; Electronic</p>
</div>
<ul class="col-md-6 col-sm-6 col-xs-6">
<li>SmartPhones</li>
<li>Laptops</li>
<li>Pen Drives</li>
<li>Memory Cards</li>
<li>All Computers &amp; Accessories</li>
<li><a href="product.html" title="View Products">View All Products</a></li>
</ul>
</div>
</div>
</div>
</div>
</section>-->

