

<script>
requirejs(['jquery'], function(jQuery){
    jQuery(function(){
        jQuery('input:radio').change(function() {
			jQuery("#kill").html('');
			var radios = document.querySelectorAll('input[type="radio"]:checked');
			
            var value = radios.length>0? radios[0].value: null;
			var price=document.getElementById("tested").value;
			
			var sum = parseInt(value) + parseInt(price);
			jQuery("#sprice").hide();
			jQuery("#kill").append('$'+sum);
			
			
		
			//alert(sum);
       
    });
    });
});
	
	

</script>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
     $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
     

         $sql_url_rewrite = "SELECT * FROM `addsubscriptionplans`";
               $result_url_rewrite = $connection->fetchAll($sql_url_rewrite);
			   
			   //Print_r($result_url_rewrite);
			 
		
			
			
			
			$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->create('Magento\Customer\Model\Session'); 
             
			

?>



<style type="text/css"> 
	
	#content { width: 1260px; margin: 40px auto; background-color: #f9f9f9; }
	
	
	/* SaaS Pricing Chart CSS: */
	
	.attr-col { margin: 110px 0 0; float: left; width: 299px; }
	.attr-col ul { background: #f4f4f4; font-weight: bold; font-size: 13px; border: 1px solid #d6d6d6; border-width: 1px 0px 1px 1px; -webkit-border-top-left-radius: 5px; -webkit-border-bottom-left-radius: 5px; -moz-border-radius-topleft: 5px; -moz-border-radius-bottomleft: 5px; border-top-left-radius: 5px; border-bottom-left-radius: 5px; }
	.attr-col ul li { text-align: right; padding: 0 10px; border-bottom: 1px solid #d6d6d6; line-height: 45px; display: block; }
	.attr-col ul li.last { border-bottom: none; }
	.pt-body {  display: block; position: relative; } 

	.pt-rows li { display: block; overflow: hidden;background: #fff; border-left: 2px solid #ccc; border-right: 2px solid #ccc; border-bottom: 1px solid #d9d9d9;  }
	.pt-rows li span { width: 24%; text-align: center; float: left; border-right: 1px solid #d9d9d9; display: block; line-height: 45px; height: 45px; }
	.pt-rows li.title { background: #666; font-size: 22px; color: #fff; font-weight: bold; -webkit-border-top-left-radius: 5px; -moz-border-radius-topleft: 5px; border-top-left-radius: 5px; border-bottom: 2px solid #555; border-width: 0 0 2px; }
	.pt-rows li.title span { line-height: 50px; height: 50px; border: none; padding: 0 1px; text-shadow: 2px 2px #444; }
	.pt-rows li.fees { border-bottom: 1px solid #ccc; }
	.pt-rows li.fees span { line-height: 48px; height: 48px; background: #f7f7f7; font-size: 34px; font-weight: 700; font-family: Georgia, Arial, sans-serif; color: #4172a5; text-shadow: 2px 2px #fff; }
	.pt-rows li span.pt-yes { background: url(http://demos.devgrow.com/pricechart/yes-no.gif) no-repeat center 12px; }
	.pt-rows li span.pt-no { background: url(http://demos.devgrow.com/pricechart/yes-no.gif) no-repeat center -38px; }
	.pt-rows li.fin { border-bottom: 2px solid #d9d9d9; -webkit-border-bottom-right-radius: 5px; -webkit-border-bottom-left-radius: 5px; -moz-border-radius-bottomright: 5px; -moz-border-radius-bottomleft: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; height: 85px; }
	.pt-rows li span.pt-3x { width: 72%; float: left; text-align: center; border: none; }
	.pt-special {  right: 0; top: 0; }
	.pt-special .pt-rows { border-radius: 5px; -webkit-border-radius: 5px; -moz-border-radius: 5px; border: 1px solid #a2b7ca; background: #f4faff; 	-moz-box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); -webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); box-shadow: 0 0 10px rgba(0, 0, 0, 0.2); padding-bottom: 10px; }
	.pt-special .pt-rows li { border-width: 0 0 1px; background: transparent; }
	.pt-special .pt-rows li.title { height: 58px; margin: 1px; background: #d0ebfe; color: #2a719d; font-size: 30px; line-height: 65px; text-align: center; border-bottom: 1px solid #bfd4e6; border-width: 0 0 1px; text-shadow: 2px 2px #e6f5ff; }
	.pt-special .pt-rows li.fees { border-bottom: 1px solid #bcd8ec; }
	.pt-special .pt-rows li.fees span { background: #ecf6fe; }
	.pt-special .pt-rows li.fin { border: none; text-align: center; }
	.pt-special .pt-rows li span { border: none; width: 100%; }
	.pt-special .pt-rows li.fin .big-button { background: #3a8bd0; top: 22px; }
	.pt-special .pt-rows li.fin .big-button:hover { background: #50a6ef; }

	/* Simple Button CSS: */
	.big-button { font-size: 24px; line-height: 50px; font-weight: 700; color: #fff; padding: 10px 20px; background: #4a980d; text-shadow: 2px 2px rgba(0, 0, 0, 0.3); border-radius: 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px; border: 1px solid #407718; text-decoration: none; position: relative; top: 18px; }
	.big-button:hover { color: #fff; -moz-box-shadow: 0 0 20px #fffc00; -webkit-box-shadow: 0 0 20px #fffc00; box-shadow: 0 0 20px #fffc00; background: #6fbb2f; }
	.big-button:active { position: relative; top: 19px; }

	</style>



<div id="content" class="container">

		<div class="price-chart col-md-12">
			<div class="attr-col col-md-4">
				<ul>
					<li>One-Off SetUp Fee:</li>
					<li>On Going fee: </li>
					<li>Business App:</li>
					<li>Own Name & Branded App:</li>
					<li>Extension Domain:</li>
					<li>Published  App:</li>
					<li>Customise Your Themes</li>
					<li>Add Your Logo:</li>
					<li>Add your products:</li>
					<li>eCommerce and logistics capability:</li>
					<li>Dashboard To Monitor Transaction:</li>
					<li>Customer Appointment Management:</li>
					<li>Customer text, voice or video:</li>
					<li>Customer Reviews Capture:</li>
					
					<li class="last">Customer Data Base:</li>
				</ul>
			</div>
			
				<div class="pt-body col-md-8">
					<?php foreach ($result_url_rewrite as $item): ?>
					
					<?php if($item['subscriptionplanid']==9) {?>
				<div class="pt-special col-md-6" >
			
					<ul class="pt-rows">
				
			
						<li class="title"><?php echo $item['name'] ?> </li>
						<li class="fees"><span> $<?php echo $item['price'] ?></span></li>
						<li><span>$<?php echo $item['price'] ?></span></li>
						
						<?php  
						if($item['ongoingfee']==2)
						{
							?>
							<li><span> NiLL</span></li>
							<?php
						}
						else
						{
								?>
							<li>   <span><?php echo $item['perannually'] ?>  Annually / <?php echo $item['permonth'] ?>  paid Monthly </span></li>
							<?php
						}
						?>
						
						
						<?php  
						if($item['ba']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['onba']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['ed']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['paa']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['ct']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['alogo']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['aypsp']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['elc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['dmt']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['cam']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['cvvc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['crc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['cd']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<li class="fin"><button type="submit" form="big-button" value="Submit">Join Now</button></li>
					
					</ul>
				
				</div>
				<?php  } else { ?>
				
				<div class="pt-special col-md-6" >
			
					<ul class="pt-rows">
				
			
						<li class="title"><?php echo $item['name'] ?> </li>
						<li class="fees"><span><input type="hidden" name="country" id="tested" value="<?php echo $item['price'] ?>">
						<div id="sprice">$<?php echo $item['price'] ?> </div> <div id="kill"> </div>  </span></li>
						<li><span>$<?php echo $item['price'] ?></span></li>
						
						<?php  
						if($item['ongoingfee']==2)
						{
							?>
							<li><span> Nil </span></li>
							<?php
						}
						else
						{
								?>
							<li><span><input type="radio" name="gender" value="<?php echo $item['perannually'] ?>"  required="required">$<?php echo $item['perannually'] ?>  Annually /<input type="radio" name="gender" value="<?php echo $item['permonth'] ?>"  required="required"> $<?php echo $item['permonth'] ?> paid Monthly </span></li>
							<?php
						}
						?>
						
						
						<?php  
						if($item['ba']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['onba']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['ed']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['paa']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['ct']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['alogo']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['aypsp']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['elc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['dmt']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['cam']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						<?php  
						if($item['cvvc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['crc']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
						
						<?php  
						if($item['cd']==1)
						{
							?>
							<li><span class="pt-yes"></span></li>
							<?php
						}
						else
						{
								?>
							<li><span class="pt-no"></span></li>
							<?php
						}
						?>
				
						<li class="fin">
						<button type="submit" form="big-button" value="Submit">Join Now</button></li>
					
					</ul>
				
				</div>
				
				<?php  } ?>
				
					<?php endforeach; ?>
				
			</div>
		</div>