<div class="header" style="padding:10px;background:#339eae;">
		<div class="header_left">
			<ul>
				<li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>Australia</li>
				<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Contact Us</li>
			</ul>	
		</div>
		<div class="header_right">
			<div class="w3_agile_login">
				<div class="cd-main-header">
					<a class="cd-search-trigger" href="#cd-search"> <span></span></a>
					<!-- cd-header-buttons -->
				</div>
				<div id="cd-search" class="cd-search">
					<form action="#" method="post">
						<input name="Search" type="search" placeholder="Search...">
					</form>
				</div>
			</div>
		</div>
			<div class="clearfix"></div>
		
	</div> 
	
<div class="header-bottom">
	<nav class="navbar navbar-default">
		<div class="navbar-header navbar-left">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="http://127.0.0.1/appsell/"><h1>App<span>'n'</span>Sell</h1></a>
		</div>	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
			<nav class="link-effect-2" id="link-effect-2">
				<ul class="nav navbar-nav">
					<li class="active"><a href="index.html"><span data-hover="Home">Home</span></a></li>
					<li><a href="about.html"><span data-hover="Builf App">Build App</span></a></li>
					<li><a href="lessons.html"><span data-hover="Pricing">Pricing</span></a></li>
					<li><a href="lessons.html"><span data-hover="Training">Training</span></a></li>
					<li><a href="lessons.html"><span data-hover="Support">Support</span></a></li>
					<li><a href="lessons.html"><span data-hover="about-us">About Us</span></a></li>
					<li><a href="lessons.html"><h4><b>Sign In</b></h4></a></li>

					<!--<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span data-hover="Short Codes">Short Codes</span> <b class="caret"></b></a>
						<ul class="dropdown-menu agile_short_dropdown">
							<li><a href="icons.html">Web Icons</a></li>
							<li><a href="typography.html">Typography</a></li>
						</ul>
					</li>-->
					</ul>
			</nav>
		</div>
		<div class="agileinfo-social-grids">
			<ul>
				<li><a href="#"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter"></i></a></li>
				<li><a href="#"><i class="fa fa-rss"></i></a></li>   
			</ul>
		</div>
	</nav>
</div>