


	<!-- footer -->


	
		<div class="w3-agile-footer">
		<div class="container">
			<div class="footer-grids">
				<div class="col-md-3 footer-grid">
					<div class="footer-grid-heading">
						<h4>Address</h4>
					</div>
					<div class="footer-grid-info">
						<p>Eiusmod Tempor inc
							<span>St Dolore Place,Australia 56777.</span>
						</p>
						<p class="phone">Phone : +1 123 456 789
							<span>Email : <a href="mailto:example@email.com">info@appnsell.com</a></span>
						</p>
					</div>
				</div>
				<div class="col-md-3 footer-grid">
					<div class="footer-grid-heading">
						<h4>Navigation</h4>
					</div>
					<div class="footer-grid-info">
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About Us</a></li>
							<li><a href="build.html">Build App</a></li>
							<li><a href="pricing.html">Pricing</a></li>
							<li><a href="training.html">Training</a></li>
							<li><a href="support.html">Support</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 footer-grid">
					<div class="footer-grid-heading">
						<h4>Features</h4>
					</div>
					<div class="w3agile_footer_grid_list">
						<ul>
								<li><i class="fa fa-angle-right" aria-hidden="true"></i> List your Products</li>
							<li><i class="fa fa-angle-right" aria-hidden="true"></i> Sell Your Products</li>
							<li><i class="fa fa-angle-right" aria-hidden="true"></i> Customise Themes</li>
							<li><i class="fa fa-angle-right" aria-hidden="true"></i> Customer Interaction</li>
							<li><i class="fa fa-angle-right" aria-hidden="true"></i> Capture Reviews</li>
					</div>
				</div>
				<div class="col-md-3 footer-grid">
					<div class="footer-grid-heading">
						<h4>Twitter Posts</h4>
					</div>
					<div class="w3agile_footer_grid_list w3agile-post">
						<ul>
							<li>Ut aut reiciendis voluptatibus <a href="#">http://appnsell.com</a> alias, ut aut.
								<span><i class="fa fa-twitter" aria-hidden="true"></i> 02 days ago</span></li>
							<li>Itaque earum rerum hic tenetur a sapiente <a href="#">http://appnsell.com</a> ut aut.
							<span><i class="fa fa-twitter" aria-hidden="true"></i> 03 days ago</span></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="agileits-w3layouts-copyright">
				<p>© 2017 App'n'Sell . All Rights Reserved | Design by <a href="http://amtechgcc.com/"> amtechgcc.com</a> </p>
			</div>
		</div>
	</di